name: Build Samples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # Use ci-base image and install only the required toolchain to save disk
    # space
    container:
      image: ghcr.io/zephyrproject-rtos/ci-base:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize West
        run: |
          west init -l .
          west update --narrow -o=--depth=1
          west zephyr-export

      - name: Install Dependencies
        run: |
          pip install -r ../zephyr/scripts/requirements.txt

      - name: Setup SDK
        # Install only the ARM and x86 toolchains to minimize download size and
        # disk usage
        run: |
          west sdk install --toolchains arm-zephyr-eabi x86_64-zephyr-elf

      - name: Build and Test
        run: |
          west twister -T app/ -T test/ --integration
